wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  project: vod
  group: ${exp_name}
  name: ${run_name}
  save_dir: "."
  offline: False
  id: null
  entity: null
  log_model: False
  prefix: ""
  job_type: "train"
  tags: [ ]